/*globals define, WebGMEGlobal*/

/**
 * Generated by VisualizerGenerator 1.7.0 from webgme on Tue Sep 25 2018 17:40:04 GMT+0900 (JST).
 */

define(['css!./styles/IFrameExampleWidget.css'], function () {
    'use strict';

    var IFrameExampleWidget,
        WIDGET_CLASS = 'i-frame-example';

    IFrameExampleWidget = function (logger, container) {
        this._logger = logger.fork('Widget');

        this._el = container;

        this._iframe = null;

        this._initialize();

        this._logger.debug('ctor finished');
    };

    IFrameExampleWidget.prototype._initialize = function () {
        var width = this._el.width(),
            height = this._el.height(),
            self = this;

        // set widget class
        this._el.addClass(WIDGET_CLASS);
    };

    IFrameExampleWidget.prototype.onWidgetContainerResize = function (width, height) {
        this._logger.debug('Widget is resizing...');
    };

    IFrameExampleWidget.prototype.addIFrame = function (desc) {
        this._iframe = $('<iframe>', {
            src: desc.iframeSrc
        });

        this._iframe.css({
            width: '100%',
            height: '100%'
        });

        this._el.append(this._iframe);
    };

    IFrameExampleWidget.prototype.safeRemoveIFrame = function () {
        if (this._iframe) {
            this._iframe.remove();
            this._iframe = null;
        }
    };

    // Adding/Removing/Updating items
    IFrameExampleWidget.prototype.addNode = function (desc) {
        this.safeRemoveIFrame();

        if (desc && desc.iframeSrc) {
            this.addIFrame(desc);
        }
    };

    IFrameExampleWidget.prototype.removeNode = function (gmeId) {
        this.safeRemoveIFrame();
    };

    IFrameExampleWidget.prototype.updateNode = function (desc) {
        if (desc && desc.iframeSrc) {
            this._logger.debug('Updating node:', desc);
            if (this._iframe) {
                if (this._iframe.attr('src') !== desc.iframeSrc) {
                    this._iframe.attr('src', desc.iframeSrc);
                }
            } else {
                this.addIFrame(desc);
            }
        } else if (this._iframe) {
            this.safeRemoveIFrame();
        }
    };

    /* * * * * * * * Visualizer life cycle callbacks * * * * * * * */
    IFrameExampleWidget.prototype.destroy = function () {
    };

    IFrameExampleWidget.prototype.onActivate = function () {
        this._logger.debug('IFrameExampleWidget has been activated');
    };

    IFrameExampleWidget.prototype.onDeactivate = function () {
        this._logger.debug('IFrameExampleWidget has been deactivated');
    };

    return IFrameExampleWidget;
});
