/*globals define, _, WebGMEGlobal*/
/**
 * Generated by VisualizerGenerator 1.7.0 from webgme on Thu Apr 12 2018 12:02:53 GMT-0500 (CDT).
 */

define([
    'js/PanelBase/PanelBaseWithHeader',
    'js/PanelManager/IActivePanel',
    'widgets/ModelManager/ModelManagerWidget',
    './ModelManagerControl',
    'js/Utils/ComponentSettings',
], function (
    PanelBaseWithHeader,
    IActivePanel,
    ModelManagerWidget,
    ModelManagerControl,
    ComponentSettings
) {
    'use strict';

    var ModelManagerPanel;

    ModelManagerPanel = function (layoutManager, params) {
        var options = {};
        //set properties from options
        options[PanelBaseWithHeader.OPTIONS.LOGGER_INSTANCE_NAME] = 'ModelManagerPanel';
        options[PanelBaseWithHeader.OPTIONS.FLOATING_TITLE] = false;

        //call parent's constructor
        PanelBaseWithHeader.apply(this, [options, layoutManager]);

        this._client = params.client;
        this._config = {};
        ComponentSettings.resolveWithWebGMEGlobal(this._config, ModelManagerPanel.getComponentId());

        //initialize UI
        this._initialize();

        this.logger.debug('ctor finished');
    };

    //inherit from PanelBaseWithHeader
    _.extend(ModelManagerPanel.prototype, PanelBaseWithHeader.prototype);
    _.extend(ModelManagerPanel.prototype, IActivePanel.prototype);

    ModelManagerPanel.getComponentId = function () {
        return 'ModelManagerPanel';
    };
    ModelManagerPanel.prototype._initialize = function () {
        var self = this;

        //set Widget title
        this.setTitle('');

        this.widget = new ModelManagerWidget(this.logger, this.$el, {inFault: false, types:['FCO','otherType']});

        this.widget.setTitle = function (title) {
            self.setTitle(title);
        };

        this.control = new ModelManagerControl({
            logger: this.logger,
            client: this._client,
            widget: this.widget
        });

        this.onActivate();
    };

    /* OVERRIDE FROM WIDGET-WITH-HEADER */
    /* METHOD CALLED WHEN THE WIDGET'S READ-ONLY PROPERTY CHANGES */
    ModelManagerPanel.prototype.onReadOnlyChanged = function (isReadOnly) {
        //apply parent's onReadOnlyChanged
        PanelBaseWithHeader.prototype.onReadOnlyChanged.call(this, isReadOnly);

    };

    ModelManagerPanel.prototype.onResize = function (width, height) {
        this.logger.debug('onResize --> width: ' + width + ', height: ' + height);
        this.widget.onWidgetContainerResize(width, height);
    };

    /* * * * * * * * Visualizer life cycle callbacks * * * * * * * */
    ModelManagerPanel.prototype.destroy = function () {
        this.control.destroy();
        this.widget.destroy();

        PanelBaseWithHeader.prototype.destroy.call(this);
        WebGMEGlobal.KeyboardManager.setListener(undefined);
        WebGMEGlobal.Toolbar.refresh();
    };

    ModelManagerPanel.prototype.onActivate = function () {
        this.widget.onActivate();
        this.control.onActivate();
        WebGMEGlobal.KeyboardManager.setListener(this.widget);
        WebGMEGlobal.Toolbar.refresh();
    };

    ModelManagerPanel.prototype.onDeactivate = function () {
        this.widget.onDeactivate();
        this.control.onDeactivate();
        WebGMEGlobal.KeyboardManager.setListener(undefined);
        WebGMEGlobal.Toolbar.refresh();
    };

    return ModelManagerPanel;
});
